[workspace]
members = ["protocol", "native", "clients/wasm", "clients/bindings", "clients/sdk"]
resolver = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
prost = "0.14.4"
thiserror = "2.0.20"
moq-core = { package = "moq-net", version = "0.3.0" }
