[package]
name = "tidkod-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository = "https://github.com/coral/tidkod"
publish = ["crates-io"]
description = "Protocol and timing core for Tidkod LAN timecode synchronization"
build = "build.rs"

[dependencies]
prost.workspace = true
thiserror.workspace = true
st12-1 = { version = "0.3.1", default-features = false }
broadcast-common = { version = "9.4", default-features = false }

[build-dependencies]
protox = "0.9.1"
prost-build = "0.14.4"
prost.workspace = true
